### ISSUE TITLE
Project- Indian Poker

### ISSUE THREAD

**Issue by pearl-jinju** [pearl-jinju/fizzbuzz-team#1]
## Repuirements
인디언 포커를 구현해보자!
1. q버튼을 누르면 언제든 종료한다.
2. 카드는 덱이 소진될때까지 보충하지 않는다.
3. 상대방은 무조건 베팅에 응한다.

## task list
- [ ] 언제나 q입력시 종료되는 조건  추가하기 (Keyboard module 활용) (이상규)
- [ ] 상대 플레이어 칩 부여 및 상대방 칩소진 시 승리조건 추가 (정진주)
- [ ] 게임 진행단계별 코드 복잡성 개선을 위한 메소드 활용 (정준녕)
- [ ] 반복성 플레이를 높일수 있는 방안 모색 (ALL -Member)
- [ ] 의사난수문제 발생 여부 확인 및 발생 시 조치 (ALL -Member)
- [ ] 기타 발견된 미비 사항 (ALL -Member)

**Comment by ulgoon** [comment]
개요로는 완벽한 issue 입니다:) 이제 각자가 나눠가진 해야 할 일들을 issue를 생성하신 뒤 fork 하여 각자 작업을 시작하시면 될 듯합니다^^

**Comment by ulgoon** [comment]
팀원님들 issue 작성하고 일하러 가셔야 해욧!
