### ISSUE TITLE
 언제나 q입력시 종료되는 조건 추가하기 (Keyboard module 활용) (이상규)

### ISSUE THREAD

**Issue by gyoo-coder** [pearl-jinju/fizzbuzz-team#3]
## Requirements

인디언 포커를 구현해보자!

1. q버튼을 누르면 언제든 종료한다.
2. 카드는 덱이 소진될때까지 보충하지 않는다.
3. 상대방은 무조건 베팅에 응한다.

## task list

- [ ] 언제나 q입력시 종료되는 조건 추가하기 (Keyboard module 활용) (이상규)
- [ ] 반복성 플레이를 높일수 있는 방안 모색 (ALL -Member)
- [ ]  의사난수문제 발생 여부 확인 및 발생 시 조치 (ALL -Member)
- [ ]  기타 발견된 미비 사항 (ALL -Member)
